### ISSUE TITLE
error: no matching function for call to ‘publishClustersCloud(ros::Publisher&, std_msgs::Header&, std::vector<boost::shared_ptr<pcl::PointCloud<pcl::PointXYZI> > >&)’

### ISSUE THREAD

**Issue by gogojjh** [LidarPerception/segmenters_lib#4]
![screenshot from 2018-06-26 10-47-17](https://user-images.githubusercontent.com/11897988/41886322-7082119c-792e-11e8-9994-12abd2da1145.png)

**Comment by Durant35** [comment]
Recommend you to update the dependent  package [LidarPerception/common_lib](https://github.com/LidarPerception/common_lib)
```bash
$ cd your-common_lib-path
$ git pull
```
