### ISSUE TITLE
issue: File "/home/shuai/catkin_segment/src/kitti_ros/scripts/kitti_player.py", line 34, in <module>     from evdev import InputDevice ImportError: No module named evdev

### ISSUE THREAD

**Issue by Xiangzhaohong** [LidarPerception/segmenters_lib#6]
File "/home/shuai/catkin_segment/src/kitti_ros/scripts/kitti_player.py", line 34, in <module>
    from evdev import InputDevice
ImportError: No module named evdev

How could I solve it?
Thanks!

**Comment by Xiangzhaohong** [comment]
ERROR: cannot launch node of type [segmenters_lib/detection_node]: can't locate node [detection_node] in package [segmenters_lib]

**Comment by Durant35** [comment]
Maybe you can try following to install **python-evdev**, which allows you to read and write input events on Linux, keyboard in this tool
```bash
$ sudo apt-get install python-evdev
```

**Comment by Xiangzhaohong** [comment]
@Durant35 Thanks!
1. I find I don't have the timestamps.txt that kitti_player.py needs, where can I get it;
2. And when I run demo.launch, it can't find the detection_node, I find it , but don't know how to deal with it.

IOError: [Errno 2] No such file or directory: '/home/shuai/catkin_segment/src/kitti_ros/../../data/2011_09_26/2011_09_26_drive_0005_sync/velodyne_points/timestamps.txt'


ERROR: cannot launch node of type [segmenters_lib/detection_node]: can't locate node [detection_node] in package [segmenters_lib]

Thanks a lot!

**Comment by Xiangzhaohong** [comment]
@Durant35 sorry I didn't see the kitti_ros for detail,  I am succeed with the kitti_player.launch.

But I still cannot launch the demo.launch in segementers_lib.

**Comment by Durant35** [comment]
Maybe you can see this repo for detail. open a new issue about that if need, for better communication.
