### ISSUE TITLE
ERROR: cannot launch node of type [segmenters_lib/detection_node]: can't locate node [detection_node] in package [segmenters_lib]

### ISSUE THREAD

**Issue by Durant35** [LidarPerception/segmenters_lib#7]
As discussed in #6

**Comment by Durant35** [comment]
@Xiangzhaohong Hope that it works, sorry for making you misunderstanding

**Comment by Xiangzhaohong** [comment]
@Durant35 Thanks a lot ! I made it work before you modified this . Thanks anyway ! And Merry Christmas !

**Comment by Samiratous** [comment]
@Xiangzhaohong how did you solve that ros cannot find the detection_node?

**Comment by Xiangzhaohong** [comment]
u could solve it in CMAKELIST




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samiratous"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 晚上6:52
收件人: "LidarPerception/segmenters_lib"<segmenters_lib@noreply.github.com&gt;; 
抄送: "卷毛"<244780602@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [LidarPerception/segmenters_lib] ERROR: cannot launch node of type [segmenters_lib/detection_node]: can&#39;t locate node [detection_node] in package [segmenters_lib] (#7)




@Xiangzhaohong how did you solve that ros cannot find the detection_node?

**Comment by Samiratous** [comment]
@Xiangzhaohong  really don't get it what I have to change or how to solve it in the cmakelist. Any suggestions? I am not a ROS expert and new to this.

**Comment by lchop** [comment]
You have to uncomment the add_subdirectory line
