### ISSUE TITLE
rviz界面什么也没有

### ISSUE THREAD

**Issue by wdxpython** [LidarPerception/segmenters_lib#8]
您好，我问一下，运行您的demo对电脑的配置要求高吗？我运行demo没有错误，但是在rviz界面一直什么也没有，终端上只提示节点开始了，是我的电脑带不动吗？

**Comment by Durant35** [comment]
have you replay the data？

**Comment by wdxpython** [comment]
> have you replay the data？

![default](https://user-images.githubusercontent.com/43343284/53932679-c0e5ad00-40d5-11e9-8003-c1f481b1ffb7.png)
是按照上面说的运行了这两个终端

**Comment by wdxpython** [comment]
> have you replay the data？

how to replay？

**Comment by Durant35** [comment]
click space to start replay, refer to https://github.com/LidarPerception/kitti_ros if having problem.

**Comment by wdxpython** [comment]
> click space to start replay, refer to https://github.com/LidarPerception/kitti_ros if having problem.

我尝试了不行，我给您发了邮件，还望您有时间看一下。

**Comment by Durant35** [comment]
I have received your e-mail, greatly appreciate to your attention. Maybe your problem can refer to this issue: https://github.com/LidarPerception/kitti_ros/issues/1

**Comment by Durant35** [comment]
Besides, have opened an issue for data replay.

**Comment by wdxpython** [comment]
> Besides, have opened an issue for data replay.

thank you very much !

**Comment by Durant35** [comment]
Close due to fixed, refer to https://github.com/LidarPerception/kitti_ros/issues/1
